### ISSUE TITLE
Replace AO integrals by libint

### ISSUE THREAD

**Issue by scemama** [LCPQ/quantum_package#150]

**Comment by eginer** [comment]
Does it mean that we do not compute AO integrals with our standard routines anymore ?

**Comment by scemama** [comment]
We will create the possibility to switch from our AOs to libint. with the `qp_install.py`
:hamburger:

**Comment by eginer** [comment]
When will this amaillzingue release be available ?! 
Other question : is there a possibility to have Cholesky bi electronic integrals within libint ?! 
This would be really amaillzingue !!

**Comment by scemama** [comment]
When : soon
Cholesky : I don't think so...
