### ISSUE TITLE
Non-standard install location?

### ISSUE THREAD

**Issue by barrymoo** [LCPQ/quantum_package#168]
I have a student looking to use this package on a HPC cluster, but I don't understand how to get this installed in a non-standard location. Some issues I have:

1. Invoking the configure process, it appears packages are automatically installed to `~/.opam/...`, which is unhelpful for other users.

2. opam has no support for building to/from non-standard locations? Is that correct? For example, https://github.com/ocaml/opam-repository/blob/master/packages/conf-zmq/conf-zmq.0.1/opam is hardcoded?

These might be opam's problems, but I don't see how to work around them coming from a non-OCaml background for this package.

**Comment by TApplencourt** [comment]
Yeah...
I see that @scemama have fill a insue in the opam repo (https://github.com/ocaml/opam/issues/2583) maybe this can help.

**Comment by TApplencourt** [comment]
Yeah...
I see that @scemama have fill a insue in the opam repo (
https://github.com/ocaml/opam/issues/2583) maybe this can help.

2016-07-13 16:15 GMT+02:00 Barry Moore <notifications@github.com>:

**Comment by barrymoo** [comment]
That fixes issue "1.", but it's hard for me to see how to deal with "2.". The `conf-zmq` package is just checking for zmq in the standard location, when does the build system grab the file I previously mentioned? Can I change it before the build process starts?

**Comment by TApplencourt** [comment]
You need  to modify you path before running opam.

```
export C_INCLUDE_PATH="${QP_ROOT}"/lib:"${C_INCLUDE_PATH}"
export LIBRARY_PATH="${QP_ROOT}"/lib:"${LIBRARY_PATH}"
export LD_LIBRARY_PATH="${QP_ROOT}"/lib:"${LD_LIBRARY_PATH}"
```

**Comment by barrymoo** [comment]
I had tried that. It works if you do this stuff on the command line, just not through opam.

**Comment by scemama** [comment]
Before running `./configure` the first time, you can set the ``OPAMROOT`` environment variable to the location where you want to put opam. For example:
```export OPAMROOT=/usr/local/opam```
Don't forget to put this in your ``quantum_package.rc`` file also.

**Comment by barrymoo** [comment]
Here is the script I run:

```
#!/usr/bin/env bash

module load gcc/4.9.3 intel/15.0.3

export OPAMROOT=$(pwd)/opam
export QP_ROOT=$(pwd)
export CPATH=$(pwd)/lib:$CPATH
export LIBRARY_PATH=$(pwd)/lib:$LIBRARY_PATH
./configure config/ifort.cfg --production
```

The issue is actually the config-zmq bit. I am working through it, I should have more time tomorrow.

**Comment by barrymoo** [comment]
I figured it out. Basically, I have the base RHEL 6 `cc` compiler (4.4.7) which doesn't deal with the environment variables correctly (apparently). I made a symbolic link to gcc (4.9.3) and it's working now. The `conf-zmq` dependency for `ocaml-zmq` is quite poor.

**Comment by scemama** [comment]
Yes. To be able to build all the dependencies you need at least GCC 4.6.

**Comment by barrymoo** [comment]
Thanks for your help!
