### ISSUE TITLE
Newer versions of sphinx cause docs build to fail.

### ISSUE THREAD

**Issue by barrymoo** [LCPQ/quantum_package#169]
I have Sphinx v1.4.1 running and ran into 2 things:

1. `WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.`
2.
```
Extension error:
Config value 'math_number_all' already present
```

Both are solved by removing `sphinx.ext.pngmath` from `doc/conf.py`, likely not a cross platform solution.

**Comment by scemama** [comment]
Thanks for mentioning this problem.
