### ISSUE TITLE
Run in Parallel?

### ISSUE THREAD

**Issue by barrymoo** [LCPQ/quantum_package#170]
Is this code designed to run over multiple nodes? Do you have an example somewhere?

**Comment by TApplencourt** [comment]
Just a quick answers before @scemama make the long one: Yes.  Unfortunately  I don't remember the how to and if this functionality is already in the main branch.

**Comment by scemama** [comment]
Hi, here is the long answer ;-)
As @TApplencourt said, it is work in progress on an experimental branch. It will come in a few weeks in the main branch.
Cheers

**Comment by scemama** [comment]
Hi!
Sorry, I forgot to reply before...

You can now run selected Full-CI calculations on multiple nodes. The selection and PT2 calculation has been tested with no problem up to ~4500 cores, and I am sure it can go much further. But we are still trying to distribute the diagonalization, but it is very diffcult to make it scale. We are working hard on that part, maybe we will abandon the Davidson algorithm...

Now, there is a Full_CI_ZMQ module where the Full_CI has been entirely re-written (much faster, and more accurate). So to make a parallel run:
1) Start a single node job:
`qp_run fci_zmq test.ezfio`

2) Submit another job on another node that will help the first one:
`qp_run -slave selection_slave test.ezfio`

You can submit as many slave jobs as you want, and they will add more and more resources to the master job.

For simplicity, you can also do in a single job:
```
srun -n 1 -N 1 qp_run fci_zmq test.ezfio &
sleep 10
srun -n 99 -N 99 qp_run selection_slave test.ezfio
wait
```
To maximize the efficiency, you should use 1 selection_slave per node. It is multi-threaded.

It is quite different from the usual MPI workflow where the resources are fixed, but it is adapted to grid computing : we have been able to mix a supercomputer with virtual machines in the 2 different clouds on the same running job. We are also working on the possibility to reduce the resources dynamically and on a way to handle properly fault tolerance.

Cheers,
Anthony

**Comment by barrymoo** [comment]
@kgasperich Could be helpful for you.
