### ISSUE TITLE
Ocaml install is broken (crypto kit)

### ISSUE THREAD

**Issue by TApplencourt** [LCPQ/quantum_package#171]
See https://api.travis-ci.org/jobs/170583935/log.txt?deansi=true

```
[ERROR] The compilation of cryptokit failed at "make".
The following actions failed
  ∗  install crypto kit 1.11
```
Sorry...

**Comment by scemama** [comment]
Did you clean the cache in travis?

**Comment by scemama** [comment]
Cleaning the cache didn't solve the problem...

**Comment by scemama** [comment]
Cryptokit v1.11 needs zarith v1.4. The default zarith installed by opam was v1.2. I forced the install of the last zarith and it works now, and I submitted a bug to the cryptokit developers. Fixed by commit c781018.

**Comment by TApplencourt** [comment]
Well done!

**Comment by TApplencourt** [comment]
Yes.
