### ISSUE TITLE
forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by artemgru** [LCPQ/quantum_package#184]
I try to compile and run with -axCORE-AVX512. Compilation was done successfully, but after the start qp_run I got **forrtl: severe (174): SIGSEGV, segmentation fault occurred**

I tried to do **ulimit -s unlimited** but it doesn;t help.

**Comment by scemama** [comment]
Hi,
There are compiler directives in the code to fix the alignment of the arrays. By default, the alignment is 256bits, which corresponds to AVX instructions. When you use AVX512, the vectors have to be 512bit aligned. So in the config file you should change
```
IRPF90_FLAGS : --ninja --align=32
```
into
```
IRPF90_FLAGS : --ninja --align=64
```
to set the proper alignment.
However, modern Xeon CPUs don't complain with misaligned data but the Xeon Phi produces a segmentation fault.  So there might be some wrong directives assuming that the data is aligned when it is not.
If you still have a segfault with the correct alignment, can you compile with `-traceback` and post the output?
Thanks

PS: I doubt that the AVX512 is going to improve the performance. The bottleneck of the program is random data access and bitwise operations.

**Comment by artemgru** [comment]
I run the app on the Xeon CPU.
My options are:
```
IRPF90_FLAGS : --ninja --align=64
FC	 : -g -traceback
FCFLAGS  : -xCORE-AVX512 -O3 -ip -ftz -g -traceback
```

All he output I can see is:
`forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
`

I tried to use **-check bound**.It helps,but gives an overhead,so it is not a way for me.

**Comment by TApplencourt** [comment]
It's strange that you don't have more information with `traceback` enable.
It's hard to debug without it.

Maybe the `traceback`message are interconnected with other message...

PS:  I know this is obvious, but you need to reload the `configure` script
after modify the '.cfg' config file to propagate the modification.


2017-02-02 6:32 GMT-06:00 artemgru <notifications@github.com>:

**Comment by scemama** [comment]
It can be due to the -O3 flag. Try again with -O2 or -O0 instead.

**Comment by artemgru** [comment]
> PS:  I know this is obvious, but you need to reload the `configure` script
> after modify the '.cfg' config file to propagate the modification.

Yes,sure,i do it everytime when I change the config file.

> It can be due to the -O3 flag. Try again with -O2 or -O0 instead.

-O2 give me the same output and nothing usefull :(

**Comment by scemama** [comment]
Can please you post
1) the output of ``cat /proc/cpuinfo`` on the machine where the code runs 
2) which executable you are trying to run (SCF, full_ci,...)
3) the complete standard output

Does it work with `-xCORE-AVX2` ?

**Comment by artemgru** [comment]
Yes,sure
1)
2)I try to run fci_zmq_nosave

Also I tried to run with -xCORE-AVX512 -O0 and the run completed successfully.
Run with -O2 or -O3 crashes with segaults.

this Is the output file:

> > 2017-02-06 03:07:38.653189-07:00
> ===============
> Quantum Package
> ===============
> 
> Git Commit: 
> Git Date  : 
> Git SHA1  : 
> 
> 
> Task server running : tcp://36.101.23.2:41279
> --------------------------------------------------------------------------------
> * Dimension of the psi arrays                               300000
> * Number of determinants                                    300000
> * mo_tot_num                                                   126
>  AO map initialized :               47341315
>  Providing the AO integrals
> --------------------------------------------------------------------------------
>  
> .. >>>>> [ WALL TIME:        1.773300 s ] [ CPU  TIME:       47.434163 s ] <<<<< ..
>  
> 
> Nuclear Coordinates (Angstroms)
> ===============================
> 
> ================ ============ ============ ============ ============
>       Atom          Charge          X            Y            Z 
> ================ ============ ============ ============ ============
> Fe                  26.000000     0.000000     0.000000     0.000000
> O                    8.000000     0.901490     0.901490    -0.901490
> O                    8.000000     0.901490    -0.901490     0.901490
> O                    8.000000    -0.901490     0.901490     0.901490
> O                    8.000000    -0.901490    -0.901490    -0.901490
> ================ ============ ============ ============ ============
> 
> Program exited with code 154.
> Wall time : 4.25124s

This is console out:

> forrtl: severe (174): SIGSEGV, segmentation fault occurred
> forrtl: severe (174): SIGSEGV, segmentation fault occurred
> forrtl: severe (174): SIGSEGV, segmentation fault occurred
> forrtl: severe (174): SIGSEGV, segmentation fault occurred
> forrtl: severe (154): array index out of bounds
> forrtl: severe (174): SIGSEGV, segmentation fault occurred
> forrtl: severe (174): SIGSEGV, segmentation fault occurred

There is a 154 error sometimes here.

> Does it work with -xCORE-AVX2 ?
Yes,it works with xCORE-AVX2, but I need xCORE-AVX512.

**Comment by scemama** [comment]
It looks like a bug because there is an ``index out of bounds`` message.
I'll check this as soon as I have access to an AVX512 CPU.

**Comment by artemgru** [comment]
> It looks like a bug because there is an index out of bounds message.

Yes, it seems so....I will try to fix it too..."Two heads are better than one head".

**Comment by scemama** [comment]
thanks!

**Comment by scemama** [comment]
You can search for ``!DIR$ VECTOR ALIGNED`` directorives which may be wrong.
You can try first to run ``H_CORE_guess`` because it goes through much less of the program.
If it passes, it is that (almost) everything about AOs is OK and the problem should be somewhere else.
The you can try to run an ``SCF``. If it is OK, it means that the problem is probably in something which has to do with the determinants.

**Comment by artemgru** [comment]
Also,I tried to run with 
OMP_NUM_THREADS=40
KMP_HW_SUBSET=2S,20C,1T

But I got:

> Unable to bind new_zmq_pull_socket (tcp)
>  tcp://*:41281                                                                  
>                                                   
> Program exited with code 255.

**Comment by artemgru** [comment]
> You can try first to run H_CORE_guess because it goes through much less of the program.
> If it passes, it is that (almost) everything about AOs is OK and the problem should be somewhere else.
> The you can try to run an SCF. If it is OK, it means that the problem is probably in something which has to do with the determinants.


H_CORE_guess is OK!
For SCF I see the same errors:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
```

**Comment by artemgru** [comment]
Finally I could get the traceback output, BUT....for --align=32

```
forrtl: severe (154): array index out of bounds
Image              PC                Routine            Line        Source
SCF                00000000006D6861  Unknown               Unknown  Unknown
SCF                00000000006D499B  Unknown               Unknown  Unknown
SCF                000000000067F2F4  Unknown               Unknown  Unknown
SCF                000000000067F106  Unknown               Unknown  Unknown
SCF                0000000000615979  Unknown               Unknown  Unknown
SCF                0000000000619D53  Unknown               Unknown  Unknown
libpthread-2.17.s  000000300240F100  Unknown               Unknown  Unknown
SCF                00000000004E18B3  general_primitive         617  ao_bi_integrals.irp.F90
SCF                00000000004DC511  ao_bielec_integra         288  ao_bi_integrals.irp.F90
SCF                00000000004EE1C4  provide_ao_bielec         203  ao_bi_integrals.irp.F90
libiomp5.so        00002ADCF2BD5D13  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002ADCF2BA5FAD  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002ADCF2B7E6F8  __kmpc_fork_call      Unknown  Unknown
SCF                00000000004EE01E  provide_ao_bielec         197  ao_bi_integrals.irp.F90
SCF                00000000004F6426  compute_ao_integr        1187  ao_bi_integrals.irp.F90
SCF                000000000055EAC3  ao_bielec_integra          84  ao_bielec_integrals_in_map_slave.irp.F90
SCF                00000000004D93F7  provide_ao_bielec         114  ao_bi_integrals.irp.F90
libiomp5.so        00002ADCF2BD5D13  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002ADCF2BA5B17  Unknown               Unknown  Unknown
libiomp5.so        00002ADCF2BA51C5  Unknown               Unknown  Unknown
libiomp5.so        00002ADCF2BD6193  Unknown               Unknown  Unknown
libpthread-2.17.s  0000003002407DC5  Unknown               Unknown  Unknown
libc-2.17.so       00000030014F6C4D  clone                 Unknown  Unknown

```

BTW, I think that for --align=64 there are the same code strings which issue the errors.

**Comment by scemama** [comment]
It is normal if it crashes with ``align=32``. I'm not sure it will be at 
the same place.

Anyway, can you put the lines around line 617 in file 
`quantum_package/plugins/Hartree_Fock/IRPF90_temp/Integrals_Bielec/ao_bi_integrals.irp.F90` 
please ?

**Comment by artemgru** [comment]
Yes,sure!

```
  !DIR$ VECTOR ALIGNED                     ! Integrals_Bielec/ao_bi_integrals.irp.f: 504
  do ix=0, iorder                          ! Integrals_Bielec/ao_bi_integrals.irp.f: 505
    Iy_pol(ix) = 0.d0                      ! Integrals_Bielec/ao_bi_integrals.irp.f: 506
  enddo                                    ! Integrals_Bielec/ao_bi_integrals.irp.f: 507

```

**Comment by scemama** [comment]
This one is correct when you use ``--align=64`` and  wrong with 
``--align=32``.

Too bad!


I found something: try to change

``SIMD_vector = 32``

into

``SIMD_vector = 64``

in the file ``Utils/constants.include.F``. This one is clearly wrong in 
your case.

**Comment by artemgru** [comment]
I used --align=64 and do ``SIMD_vector = 64`` and get the same error:

```
forrtl: severe (154): array index out of bounds
Image              PC                Routine            Line        Source
SCF                00000000006D6861  Unknown               Unknown  Unknown
SCF                00000000006D499B  Unknown               Unknown  Unknown
SCF                000000000067F2F4  Unknown               Unknown  Unknown
SCF                000000000067F106  Unknown               Unknown  Unknown
SCF                0000000000615979  Unknown               Unknown  Unknown
SCF                0000000000619D53  Unknown               Unknown  Unknown
libpthread-2.17.s  000000300240F100  Unknown               Unknown  Unknown
SCF                00000000004E18B3  general_primitive         617  ao_bi_integrals.irp.F90
SCF                00000000004DC511  ao_bielec_integra         288  ao_bi_integrals.irp.F90
SCF                00000000004EE1C4  provide_ao_bielec         203  ao_bi_integrals.irp.F90
libiomp5.so        00002AD8A1CE0D13  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002AD8A1CB0FAD  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002AD8A1C896F8  __kmpc_fork_call      Unknown  Unknown
SCF                00000000004EE01E  provide_ao_bielec         197  ao_bi_integrals.irp.F90
SCF                00000000004F6426  compute_ao_integr        1187  ao_bi_integrals.irp.F90
SCF                000000000055EAC3  ao_bielec_integra          84  ao_bielec_integrals_in_map_slave.irp.F90
SCF                00000000004D93F7  provide_ao_bielec         114  ao_bi_integrals.irp.F90
libiomp5.so        00002AD8A1CE0D13  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002AD8A1CB0B17  Unknown               Unknown  Unknown
libiomp5.so        00002AD8A1CB01C5  Unknown               Unknown  Unknown
libiomp5.so        00002AD8A1CE1193  Unknown               Unknown  Unknown
libpthread-2.17.s  0000003002407DC5  Unknown               Unknown  Unknown
libc-2.17.so       00000030014F6C4D  clone                 Unknown  Unknown

```

**Comment by artemgru** [comment]
> ``SIMD_vector = 64``

I tried but the errors are the same

**Comment by scemama** [comment]
Good, so now you get the "out of bounds" error with ``--align=64`` and ``SIMD_vector=64``, right?
If I remember, with   ``--align=64`` you didn't get any diagnostic before, so we are getting closer.

**Comment by artemgru** [comment]
Yes,you are right!

**Comment by scemama** [comment]
In the file where you changed the SIMD_vector value, there is a ``max_dim`` constant set to 511. Does it work if you set this constant to 1023? Before recompiling, in the Hartree_Fock directory, run ``ninja clean``

**Comment by artemgru** [comment]
I try to do this but:
`ninja: error: loading 'build.ninja': No such file or directory`

**Comment by scemama** [comment]
I just ran the Intel Software Development Emulator to simulate a Skylake 
server CPU, and everything worked fine. Can you try on a smaller system, 
like a water molecule with the cc-pvdz basis set?

**Comment by artemgru** [comment]
```
My CPU is:
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          2
CPU family:            6
Stepping:              2
CPU MHz:               1801.000
BogoMIPS:              3595.85
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              33792K

```

**Comment by artemgru** [comment]
> Can you try on a smaller system,
> like a water molecule with the cc-pvdz basis set?

I am not sure about it

**Comment by artemgru** [comment]
> I just ran the Intel Software Development Emulator to simulate a Skylake
> server CPU

What are the configurations of your simulated CPU?

**Comment by scemama** [comment]
-skx                Set chip-check and CPUID for Skylake Server
which is OK with `-xCORE-AVX512`.
If I run the executable without the SDE, it gives (on a Haswell CPU) :
```
Please verify that both the operating system and the processor support Intel(R) AVX512DQ, AVX512F, ADX, RDSEED, AVX512CD, AVX512BW and AVX512VL instructions.
```


I also used the `-align_checker assert` flag to make it crash for mis-aligned data, and everything worked fine.

**Comment by artemgru** [comment]
Hmmm, it is so strange.
Could it be because of the input?

**Comment by artemgru** [comment]
> Can you try on a smaller system,
> like a water molecule with the cc-pvdz basis set?

So,my .xyz file is:
```
5
Td 
Fe      -0.00000     -0.00000      0.00000
 O       0.90149      0.90149     -0.90149
 O       0.90149     -0.90149      0.90149
 O      -0.90149      0.90149      0.90149
 O      -0.90149     -0.90149     -0.90149
```

I do `qp_create_ezfio_from_xyz test.xyz -b def2-svpd -o test`. It is OK!
BUT,when I do `qp_run SCF test` I am getting the errors:

```
 forrtl: severe (174): SIGSEGV, segmentation fault occurred
 forrtl: severe (174): SIGSEGV, segmentation fault occurred
 forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
 forrtl: severe (174): SIGSEGV, segmentation fault occurred ~  1.35115h left
 forrtl: severe (174): SIGSEGV, segmentation fault occurred
 Program exited with code 174.
```

**Comment by scemama** [comment]
OK, try with this xyz file:
```
cat << EOF > f2.xyz
2
F2 
F    0.0    0.0    0.0
F    0.0    0.0    1.4119
EOF
```

and run 
```
qp_create_ezfio_from_xyz f2.xyz -b cc-pvdz -o f2
qp_run SCF f2
```

Does it still crash?

**Comment by artemgru** [comment]
I tried to build and run it on KNL.
`FCFLAGS  : -xCORE-AVX512 -O3 -ip -ftz -g -traceback`
But, when I run qp_run, I am getting:

> Please verify that both the operating system and the processor support Intel(R) AVX512DQ, AVX512BW and AVX512VL instructions.

So,I don't see the causes for it.KNL of course supports -xCORE-AVX512

**Comment by artemgru** [comment]
> Does it still crash?

OK,I will try it little bit later.

**Comment by scemama** [comment]
It seems to me that for KNL you need `-xMIC-AVX512`.
The simulator gives the same error message when running the xCORE-AVX512 code on a simulated KNL.

**Comment by TApplencourt** [comment]
I check the flags supported by my KNL. And yes they don't support AVX512DQ,
AVX512BW and AVX512VL instructions. Only `avx512f  avx512pf avx512er
avx512cd`.

2017-02-06 11:37 GMT-06:00 Anthony Scemama <notifications@github.com>:

**Comment by artemgru** [comment]
> qp_create_ezfio_from_xyz f2.xyz -b cc-pvdz -o f2
> qp_run SCF f2
> Does it still crash?

Yes, still the same error:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred ~  34.3044s left
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Program exited with code 174.
```

**Comment by artemgru** [comment]
I checked on my KNL and there are no these errors.SO,I see these errors only for xCORE-AVX512.

**Comment by artemgru** [comment]
So, i decided that I will try to reduce the problem.Now,I am knowing that the problem is located inside SCF run.
Can I somehow else to reduce the problem zone? Maybee compile and run smaller parts of code independently to find where the problem is located?

**Comment by artemgru** [comment]
> It seems to me that for KNL you need -xMIC-AVX512.
> The simulator gives the same error message when running the xCORE-AVX512 code on a simulated KNL.

I have a question!
Could the "Energy of state    1" number be different when I run with the different options,like xCORE-AVX2 and xCORE-AVX512 ?

**Comment by artemgru** [comment]
I found out that when I run with AVX2 all runs currently, but when I use AVX512 the number of the determinants starts to changing somehow... In the start of program this number is 1.....then 1022...then 16352.....65408....261632 and 600000 at the end of program.

But for the AVX2 this number is the 300000 ALWAYS and the 600000 at the end of program!
Can this fact led somehow to the errors or deviations in results which I get??
