### ISSUE TITLE
python 2.6 and 2.7

### ISSUE THREAD

**Issue by kencat** [LCPQ/quantum_package#185]
The ninja can not be run on the python 2.6. 

It will show this:
 File "install/p_graphviz/graphviz/backend.py", line 13
    'dot', 'neato', 'twopi', 'circo', 'fdp', 'sfdp', 'patchwork', 'osage',
         ^
SyntaxError: invalid syntax

That because the 2.7 changed the “set” grammar.
So change the {}  -> set([])  it will work on python 2.6.

Thank you very much.

**Comment by TApplencourt** [comment]
Thank you for you report !

I appear that the library we use for  the `graphviz` API (https://github.com/xflr6/graphviz/) has dropped the support of python 2.6 recently.

To circumvent, we will do `try / except` and display an warning message is the Python version is incompatible with the graphviz library. 
This library is optional and should not cause the installation/compilation of the program to failed. My bad, I was young when I design this.

I will push a pull-request soon.
Thank you again!
