### ISSUE TITLE
diagonal_fock_matrix_mo DSYEV failed 

### ISSUE THREAD

**Issue by TApplencourt** [LCPQ/quantum_package#205]
```
==== ================ ================ ================
  N          Energy      Energy diff       DIIS error  
==== ================ ================ ================
   1   -73.3289600594    -3.3679102478     1.5345210988   1
   2   -75.8153324935    -2.4863724340     0.4941942881   2
   3   -75.9927607442    -0.1774282507     0.2000413019   3
   4   -76.0267716997    -0.0340109555     0.0148093122   4
   5   -76.0269671012    -0.0001954015     0.0094168148   5
   6   -76.0269945391    -0.0000274379     0.0064106990   6
   7   -76.0270117148    -0.0000171757     0.0064208071   0
   8   -76.0270185583    -0.0000068435     0.0021485850   1
   9   -76.0270207855    -0.0000022272     0.0012824848   0
  10   -76.0270215141    -0.0000007286     0.0007126159   1
  11   -76.0270217529    -0.0000002387     0.0004170890   0
  12   -76.0270218311    -0.0000000783     0.0002351910   1
  13   -76.0270218568    -0.0000000257     0.0001361552   0
 diagonal_fock_matrix_mo DSYEV failed :           23
STOP 1
Program exited with code 1.
Wall time : 3.19975s
```
This error seem not related to this particular pull request, but more about the new DIIS ( @scemama )

# Error code meaning

The error code for DSYEV mean (http://www.netlib.org/lapack/explore-html/d2/d8a/group__double_s_yeigen_ga442c43fca5493590f8f26cf42fed4044.html):
```
          > 0:  if INFO = i, the algorithm failed to converge; i
                off-diagonal elements of an intermediate tridiagonal
                form did not converge to zero.
```
So In our case we have 23    off-diagonal elements of an intermediate tridiagonal form did not converge to zero....

# Energy comparison with last correct build
If we compare with the last last correct CI build:
```
  13   -76.0270218502    -0.0000000257     0.0002923517   0
```
The energy seem correct (delta of 1E-8) but the DIIS error is quite different (1E-4 in absolute but x2 in relative)...

# Full Trace

https://travis-ci.org/LCPQ/quantum_package/builds/247562613?utm_source=github_status&utm_medium=notification

PS: I'm pretty sure that, if I re-run the tests they will pass.

**Comment by TApplencourt** [comment]
(just for have an Issue number to reference in the commit)

**Comment by scemama** [comment]
This is a bug of the Lapack version of Travis. I changed the test to avoid the problem.
