### ISSUE TITLE
Excited states (From Ken Jordan's group)

### ISSUE THREAD

**Issue by anbenali** [LCPQ/quantum_package#212]
Hello 
From Amanda Dumi, a grad student in Ken Jordan's group on the excited states!! Apparently, the n_states tags does not do anything and keeps resending the ground state. 

======

Thank you for taking a look at the input files. The issue is when fci_zmq calculation is ran for n_states >1, only one determinant is kept, returning the Hartee-Fock energy. fci_zmq does seem to work for n_state = 1. I have attached the input xyz file and the ezfio summary. I have also included output from the SCF calculation (h2o_scf_out.txt) , fci_zmq on a single state (h2o_fcizmq_out.txt), and fci_zmq on and n_states >1 (h2o_fcizmp_excited_out.txt). I generated the ezfio files as instructed by Dr. Scemama:

qp_create_ezfio_from_xyz -b 3-21g h2o.xyz
qp_run SCF h2o.ezfio
qp_set_frozen_core.py h2o.ezfio
qp_edit h2o.ezfio  # here I simply change n_states=1 to n_states = 2
qp_run fci_zmq h2o.ezfio

I have also attempted to increase the number of states in the diagonalization and setting the s2_eig variable to false, but these approaches have not resolved the issue.
Thank you,
Amanda Dumi

@scemama 

==============
[h2o_fcizmq_excited_out.txt](https://github.com/LCPQ/quantum_package/files/1314936/h2o_fcizmq_excited_out.txt)
[h2o_fcizmq_out.txt](https://github.com/LCPQ/quantum_package/files/1314937/h2o_fcizmq_out.txt)
[h2o_scf_out.txt](https://github.com/LCPQ/quantum_package/files/1314939/h2o_scf_out.txt)
[qp_edit_summary.txt](https://github.com/LCPQ/quantum_package/files/1314940/qp_edit_summary.txt)

**Comment by TApplencourt** [comment]
The amazing @scemama  pull request (#213) fix this, right?
