### ISSUE TITLE
Better treatment of environment variables in quantum_package.rc

### ISSUE THREAD

**Issue by prckent** [LCPQ/quantum_package#215]
Modest improvement request:

Don't add leading colons (:) when environment variables are not already set.
e.g. `export C_INCLUDE_PATH="${C_INCLUDE_PATH}":"${QP_ROOT}"/include
` adds a leading colon when C_INCLUDE_PATH is not already set. Apparently this breaks some Perl installation/builds.  See https://github.com/LLNL/spack/issues/6028 , https://serverfault.com/questions/145288/make-error-when-compiling-perl-5-12-1-rhel-5-5

**Comment by TApplencourt** [comment]
Thanks for the feedback.  It's now fixed!
