### ISSUE TITLE
Compiling the Fortran

### ISSUE THREAD

**Issue by mohammadreza-hosseini** [LCPQ/quantum_package#229]
Hello,

I did the standard installation step by step and I got the following error when I did compilation. Could you please help me out to see what is the problem.

Thanks in advance.

shosseini@pcal018:~/quantum_package-master> ninja
[1/3] Compiling all modules
[21/160] Create /home/shosseini/quantum_package-master/lib/libezfio_irp.a
[1/2] Building Fortran library
[2/6] Compiling Fortran files
ninja: Entering directory `src/IRPF90_temp'
[1/4] F   : libezfio_groups.irp.F90 -> libezfio_groups.irp.o
[2/4] F   : libezfio_groups.irp.F90 -> libezfio_groups
[3/4] F   : irp_touches.irp.F90 -> irp_touches.irp.o
[4/4] Link: irpf90.a
[6/6] Building Ocaml module
[106/160] Create all the binaries from Hartree_Fock
[186/189] Link: localize_mos
gfortran: error: /home/shosseini/quantum_package-master/lib/libzmq.a: No such file or directory
[187/189] Link: Huckel_guess
gfortran: error: /home/shosseini/quantum_package-master/lib/libzmq.a: No such file or directory
[188/189] Link: SCF_old
gfortran: error: /home/shosseini/quantum_package-master/lib/libzmq.a: No such file or directory
[189/189] Link: SCF
gfortran: error: /home/shosseini/quantum_package-master/lib/libzmq.a: No such file or directory
[108/160] Running IRPF90 for Integrals_Bielec
FAILED: /home/shosseini/quantum_package-master/plugins/Hartree_Fock/Huckel_guess /home/shosseini/quantum_package-master/plugins/Hartree_Fock/localize_mos /home/shosseini/quantum_package-master/plugins/Hartree_Fock/SCF /home/shosseini/quantum_package-master/plugins/Hartree_Fock/SCF_old 
cd /home/shosseini/quantum_package-master/plugins/Hartree_Fock/IRPF90_temp ; ninja /home/shosseini/quantum_package-master/plugins/Hartree_Fock/Huckel_guess /home/shosseini/quantum_package-master/plugins/Hartree_Fock/localize_mos /home/shosseini/quantum_package-master/plugins/Hartree_Fock/SCF /home/shosseini/quantum_package-master/plugins/Hartree_Fock/SCF_old && for i in /home/shosseini/quantum_package-master/plugins/Hartree_Fock/Huckel_guess /home/shosseini/quantum_package-master/plugins/Hartree_Fock/localize_mos /home/shosseini/quantum_package-master/plugins/Hartree_Fock/SCF /home/shosseini/quantum_package-master/plugins/Hartree_Fock/SCF_old ; do [ -x $i ] && touch $i ; done
[110/160] Running IRPF90 for Integrals_Bielec
ninja: build stopped: subcommand failed.
FAILED: all 
ninja -f /home/shosseini/quantum_package-master/config/build.ninja
ninja: build stopped: subcommand failed.

**Comment by TApplencourt** [comment]
Hi,
Thanks for using Quantum Package

The error message show that you don't have `libzmq` installed. 
```
home/shosseini/quantum_package-master/lib/libzmq.a
```

Can you please try the `./configure.py` again and see if you have any error during the installation of `libzmq`.

**Comment by mohammadreza-hosseini** [comment]
Thank you for the reply.

I did `./configure config/gfortran.cfg` again and installation went without any error but two warnings:


WARNING: you have a different version of opam installed at /home/shosseini/quantum_package/bin/opam                                  
It is highly recommended that you remove it.                                                                                         
Initializing with compiler 4.06.0                                                                                                    
Checking for available remotes: rsync and local, git.                                                                                
  - you won't be able to use mercurial repositories unless you install the hg                                                        
    command on your system.                                                                                                          
  - you won't be able to use darcs repositories unless you install the darcs                                                         
    command on your system.                                                                                                          
                                                                                                                                     
[WARNING] Recommended external solver aspcud not found.

**Comment by rvexiau** [comment]
I had a similar problem previously where, if I remember well, some libraries were installed in a "lib64/" folder but ninja was looking for them in "lib/". Just copying the files into the lib folder solved the issue.

I don't know if it's the same problem here or what was causing this behavior.

**Comment by mohammadreza-hosseini** [comment]
@rvexiau Thanks. It seems that I had encountered the same problem, and it is working.

**Comment by TApplencourt** [comment]
Thanks for the tips! I will try to fix it on our end.
