### ISSUE TITLE
Error in PT2

### ISSUE THREAD

**Issue by mcbennet** [LCPQ/quantum_package#235]
Hi,

For the Cl atom (with pseudopotential), I am currently attempting to run fci_zmq on HF MOs with QZ quality basis set. I have set the n_det_max to 10^7. 

After 16 hours of runtime, I see the following failure:

`pt2_collector: Error in sending abort signal (2)`

I would be grateful for any direction for how I might resolve this.

**Comment by scemama** [comment]
Hi Chandler,
I think I fixed this one in my experimental branch. Can you try it and tell me if it works better?
https://github.com/scemama/quantum_package
In any case, I plan to merge it at the beginning of the July.
Best,
Anthony
