### ISSUE TITLE
forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by ramsamojkewat313** [LCPQ/quantum_package#248]
Hi all,
I am new user of Wien2k. I am getting a segmentation fault as given below when I submit a job using the PBS job script on the compute node.

**_### setrlimit(): WARNING: Cannot raise stack limit, continuing: Invalid argument
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
lapw0              00000000004D9ECD  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F0D63F69100  Unknown               Unknown  Unknown
lapw0              00000000004AB129  xcpot1_                     1  xcpot1.f
lapw0              0000000000464699  MAIN__                   2295  lapw0.F
lapw0              00000000004042DE  Unknown               Unknown  Unknown
libc-2.17.so       00007F0D5B264B15  __libc_start_main     Unknown  Unknown
lapw0              00000000004041E9  Unknown               Unknown  Unknown
grep: *scf1*: No such file or directory
grep: lapw2*.error: No such file or directory_**

I am using the Intel compiler and libraries (2018 version). Please will you suggest me what is the source of this error? Thanks in advance.

**Comment by TApplencourt** [comment]
Hi,
We are not Wien2k. 
You may want to use their mailing list to contact hem: http://susi.theochem.tuwien.ac.at/reg_user/mailing_list/
Regards,
