### ISSUE TITLE
ocaml

### ISSUE THREAD

**Issue by TApplencourt** [LCPQ/quantum_package#37]
make dans ocaml

```
rm -f -- test_atom
ocamlbuild -j 0 -syntax camlp4o -cflags "-g -warn-error A" -lflags "-g -warn-error A"  test_atom.byte  -use-ocamlfind  
+ ocamlfind ocamlc -c -g -warn-error A -thread -package core,sexplib.syntax,cryptokit -syntax camlp4o -o Point3d.cmi Point3d.mli
File "Point3d.mli", line 14, characters 26-50:
Error: Unbound module Qptypes.Positive_float
Command exited with code 2.
Compilation unsuccessful after building 12 targets (0 cached) in 00:00:00.
make[1]: *** [test_atom.byte] Error 10
make[1]: Leaving directory `/home/razoa/quantum_package/ocaml'
make: *** [build] Error 2
```

**Comment by TApplencourt** [comment]
Je n'ai rien changer mais je l'ai plus...

**Comment by TApplencourt** [comment]
Make build give this error

**Comment by scemama** [comment]
C'est le Qptypes.ml qui n'a pas ete genere par le qptypes_geenrator.byte

**Comment by eginer** [comment]
Salut Toto, 

Y a un soucis apparemment dans la compilation du ocaml (toute dernière version su QP sur github) : 


rm -f -- test_atom
ocamlbuild -j 0 -syntax camlp4o -cflags "-g -warn-error A" -lflags "-g -warn-error A"  test_atom.byte  -use-ocamlfind  
+ ocamlfind ocamldep -package core,sexplib.syntax,cryptokit -syntax camlp4o -modules Qptypes.ml > Qptypes.ml.depends
ocamlfind: Package `core' not found
Command exited with code 2.
Compilation unsuccessful after building 8 targets (7 cached) in 00:00:00.
make[1]: *** [test_atom.byte] Erreur 10

Si t'as une idée ! :)

A + 

Toto
 

Date: Wed, 25 Mar 2015 13:13:48 -0700

**Comment by TApplencourt** [comment]
My bad. Je me suis retrouvé dans un cas chelou. Ca ne devrais jamais arriver.
