### ISSUE TITLE
Add doc to qp_convert.py and rename it

### ISSUE THREAD

**Issue by TApplencourt** [LCPQ/quantum_package#57]
Hi @eginer @scemama,

I don't know what `qp_convert.py` doing. I guess is convert  somme file who can be recognize by `result_file utility ` to `EZFIO`, but i not sure.

 * Can we set a explicit name to this script and add a few documentation? Maybe a `qp_convert_output_to_ezfio.py `.  (Cause we a have a `qp_convert_ezfio_v1_to_v2.sh` so it is a little tedious to have a  `qp_convert.py`)

Long&explicit name for conversion script are relevant i think.

* Move it to the the `/script/ezfio_interface` folder seem logical too. (All the stuff related to the ezfio need to go inside).

Have a nice day,

PS : I can do the change if you want. I was just asking, because is not my script : )

Thomas

**Comment by scemama** [comment]
OK for ``qp_convert_output_to_ezfio.py`` !
